apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-client-root #pvc的名字需要和deployment.yaml中的名字相同
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
