kind: ConfigMap
apiVersion: v1
metadata:
  name: rocketmq-broker-config
  namespace: ly01
data:
  BROKER_MEM: ' -Xms2g -Xmx2g -Xmn1g '
  broker-common.conf: |-
    brokerClusterName = DefaultCluster
    brokerName = broker-0
    brokerId = 0
    deleteWhen = 04
    fileReservedTime = 48
    brokerRole = ASYNC_MASTER
    flushDiskType = ASYNC_FLUSH
    brokerIP1 = 192.168.0.71
    #Broker 对外服务的监听端口
    listenPort=10921
    ##主要用于slave同步master
    fastListenPort=10929
    ##haService中使用
    haListenPort=10922
