apiVersion: v1
data:
  kibana.yml: >
    server.host: "0.0.0.0"
    server.shutdownTimeout: "5s"
    elasticsearch.hosts: ["http://10.233.90.90:9200"]
    elasticsearch.username: "kibana_system"
    elasticsearch.password: "McS^Rm9%z3"
    i18n.locale: "zh-CN"
kind: ConfigMap
metadata:
  labels:
    app: kibana
  name: kibana-config
  namespace: ly01
---
# kibana-deployment.yaml
# 参考链接：https://juejin.cn/post/7221075271201980474
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: ly-dev-kibana
  namespace: ly01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: 'http://10.233.90.90:9200'
            - name: ELASTICSEARCH_USER
              value: kibana_system
            - name: ELASTICSEARCH_PASSWORD
              value: McS^Rm9%z3
          image: 'kibana:7.17.13'
          imagePullPolicy: IfNotPresent
          name: kibana
          ports:
            - containerPort: 5601
              name: webinterface
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/kibana/config/kibana.yml
              name: config
              readOnly: true
              subPath: kibana.yml
      volumes:
        - configMap:
            defaultMode: 420
            name: kibana-config
          name: config

