apiVersion: v1
kind: PersistentVolume
metadata:
  name: fz-mysql
spec:
  capacity:
    storage: 340Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data
    server: 192.168.0.70
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fz-es
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data
    server: 192.168.0.70
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fz-mq
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data
    server: 192.168.0.70
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fz-minio
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data
    server: 192.168.0.70

