apiVersion: v1
kind: PersistentVolume
metadata:
  name: fz-mq-namesrv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data
    server: 192.168.0.70
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fz-mq-broker
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data
    server: 192.168.0.70
