kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: rocketmq-name-service01
  namespace: zdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-name-service01
      name_service_cr: rocketmq-name-service01
  template:
    metadata:
      labels:
        app: rocketmq-name-service01
        name_service_cr: rocketmq-name-service01
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: rocketmq-name-service01
          image: 'apache/rocketmq:4.9.4'
          command:
            - /bin/sh
          args:
            - mqnamesrv
          ports:
            - name: tcp-9876
              containerPort: 9876
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: rocketmq-namesrv-storage01
              mountPath: /home/rocketmq/logs
              subPath: zdevops-mq-namesvr01/logs
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
  - metadata:
      name: rocketmq-namesrv-storage01
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 10Gi
  serviceName: ''
---
kind: Service
apiVersion: v1
metadata:
  name: rocketmq-name-server-service01
  namespace: zdevops
spec:
  ports:
    - name: tcp-9876
      protocol: TCP
      port: 9876
      targetPort: 9876
  selector:
    name_service_cr: rocketmq-name-service01
  type: ClusterIP
