kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: rocketmq-broker-a-s-slave
  namespace: zdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-broker-a-s
      broker_cr: rocketmq-broker-a-s
  template:
    metadata:
      labels:
        app: rocketmq-broker-a-s
        broker_cr: rocketmq-broker-a-s
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: rocketmq-broker-a-s
          configMap:
            name: rocketmq-broker-a-s
            items:
              - key: broker-common.conf
                path: broker-common.conf
            defaultMode: 420
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-runbroker-sh
          configMap:
            name: runbroker-sh
            defaultMode: 420
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
        - name: rocketmq-broker
          image: 'apache/rocketmq:4.9.4'
          command:
            - /bin/sh
          args:
            - mqbroker
            - "-c"
            - /home/rocketmq/conf/broker-common.conf
          ports:
            - name: tcp-vip-10949
              containerPort: 10949
              protocol: TCP
            - name: tcp-main-10941
              containerPort: 10941
              protocol: TCP
            - name: tcp-ha-10942
              containerPort: 10942
              protocol: TCP
          env:
            - name: NAMESRV_ADDR
              value: 'rocketmq-name-server-service01.zdevops:9876;rocketmq-name-server-service02.zdevops:9876'
            - name: BROKER_MEM
              valueFrom:
                configMapKeyRef:
                  name: rocketmq-broker-a-s
                  key: BROKER_MEM
          resources:
            limits:
              cpu: 500m
              memory: 10Gi
            requests:
              cpu: 250m
              memory: 4Gi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: rocketmq-broker-a-s-storage
              mountPath: /home/rocketmq/logs
              subPath: zdevops-mq-broker-a-s/logs/broker-0-slave
            - name: rocketmq-broker-a-s-storage
              mountPath: /home/rocketmq/store
              subPath: zdevops-mq-broker-a-s/store/broker-0-slave
            - name: rocketmq-broker-a-s
              mountPath: /home/rocketmq/conf/broker-common.conf
              subPath: broker-common.conf
            - name: volume-runbroker-sh
              mountPath: /home/rocketmq/rocketmq-4.9.4/bin/runbroker.sh
              subPath: runbroker.sh
          imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: rocketmq-broker-a-s-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: "nfs"
        volumeMode: Filesystem
  serviceName: ''
